{% set name = "commlib-py" %}
{% set version = "0.13.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/robotics-4-all/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
    sha256: fbf30144ef79c84bde417a6af3910acd01a08f926e85fd181d5a3372e74ad1d5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --use-pep517 -vvv
  number: 0

requirements:
  host:
    - pip
    - poetry-core
    - python {{ python_min }}
  run:
    - redis-py >=5.0.1
    - rich >=13.7.0
    - paho-mqtt <2.0.0
    - pika >=1.3.1
    - pydantic >=2.0.0
    - python >={{ python_min }}
    - requests >=2.32.0
    - ujson >=5.7.0
test:
  imports:
    - commlib
  requires:
    - pip
    - pytest
    - python {{ python_min }}
  source_files:
    - tests
  commands:
    - pip check
    - pytest --ignore=tests/mqtt --ignore=tests/redis -v

about:
  home: https://github.com/robotics-4-all/commlib-py
  summary: "Internal DSL for communication and messaging in CyberPhysical Systems"
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - klpanagi
    - MementoRC
