{% set name = "commlib-py" %}
{% set version = "0.11.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/robotics-4-all/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 6c3c675645bb15e995529c8ba55150f556beb4f3b915094638193dacb1ae6bb3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --use-pep517 -vvv
  number: 0

requirements:
  host:
    - pip
    - poetry-core
    - python >=3.7.0
  run:
    - redis >=5.0.1
    - rich >=13.7.0
    - paho-mqtt >=1.6.1
    - pika >=1.3.1
    - pydantic >=2.0.0
    - python >=3.7.0
    - requests >=2.1.0
    - ujson >=5.7.0
test:
  imports:
    - commlib
  requires:
    - coverage
    - pip
  source_files:
    - tests
  commands:
    - pip check
    - coverage run -m unittest discover tests

about:
  home: https://github.com/robotics-4-all/commlib-py
  summary: "Internal DSL for communication and messaging in CyberPhysical Systems"
  license: MIT
  license_file:
    - LICENSE.txt
    - LICENSE

extra:
  recipe-maintainers:
    - klpanagi
    - MementoRC
