{% set name = "commlib-py" %}
{% set version = "0.10.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/robotics-4-all/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 2e7c7bf962d1ddc1f7349240d87703084d58762d2bebbe6082344783c9d466c9
    patches:
      - fix-requirements.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --use-pep517 -vvv
  number: 0

requirements:
  host:
    - pip
    - poetry-core
    - python {{ python_min }}
  run:
    - hiredis ==2.2.3
    - redis-py >=5.0.1
    - rich >=13.7.0
    - paho-mqtt <2.0.0
    - pika >=1.3.1
    - pydantic ==1.10.4
    - python >={{ python_min }}
    - requests >=2.1.0
    - ujson ==5.7.0
test:
  imports:
    - commlib
  requires:
    - coverage
    - pip
    - python {{ python_min }}
  source_files:
    - tests
  commands:
    - pip check
    - coverage run -m unittest discover tests

about:
  home: https://github.com/robotics-4-all/commlib-py
  summary: "Internal DSL for communication and messaging in CyberPhysical Systems"
  license: MIT
  license_file:
    - LICENSE.txt
    - LICENSE

extra:
  recipe-maintainers:
    - klpanagi
    - MementoRC
